import Head from "next/head";
import { useState } from "react";
import CategoryCart from "../components/CategoryCart";
import Header from "../components/header";

export default function Home({ data }) {
  return (
    <>
      <div className="max-w-md mx-auto mt-3 flex flex-col justify-center">
        <Header />
        <div className="w-full text-right px-2 mt-10 text-xl font-semibold text-red-500">
          دسته بندی
          {data.map((category) => (
            <CategoryCart key={category} data={category} />
          ))}
        </div>
        <div className="flex flex-col justify-center mx-auto w-full"></div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </>
  );
}

// This gets called on every request
export async function getServerSideProps() {
  const res = await fetch("http://localhost:8000/graphql", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(query),
  });

  const result = await res.json();

  const data = result.data.allCategory;

  // Pass data to the page via props
  return { props: { data } };
}

const query = {
  query: `
        {
          allCategory {
            name
            shortInfo
            cover
          } 
        }
      `,
  variables: {
    now: new Date().toISOString(),
  },
};
