import Head from "next/head";
import CategoryCart from "../components/CategoryCart";
import Header from "../components/header";

export default function Home() {
  return (
    <>
      <div className="max-w-md mx-auto mt-3 flex flex-col justify-center">
        <Header />
        <div className="w-full text-right px-2 mt-10 text-3xl font-black text-red-500">
          دسته بندی
        </div>
        <div className="flex flex-col justify-center mx-auto w-full">
          {[1, 2, 3, 4, 3, 5].map((item) => (
            <CategoryCart key={item} />
          ))}
        </div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </>
  );
}
